name: Test V2Ray Keys and Upload to R2 & GitHub

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  test-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          persist-credentials: false

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run V2Ray Key Tester Script
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python test_v2ray_keys.py

      - name: Verify log file existence
        run: |
          if [ -f subscription/job-logs.txt ]; then
            echo "Log file exists: subscription/job-logs.txt"
          else
            echo "Log file does not exist!"
            exit 1
          fi

      - name: Upload logs for debugging
        uses: actions/upload-artifact@v4.6.2 # Replace with a stable version
        with:
          name: script-logs
          path: subscription/job-logs.txt
