# Inside test-and-upload job:
steps:
  # ... (checkout, setup-python steps) ...

  - name: Install Python dependencies
    run: pip install -r requirements.txt # Assuming requirements.txt is in root

  - name: Run V2Ray Key Tester Script
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # <--- Add this env block
    run: python test_v2ray_keys.py # Assuming .py is in root

  # ... (rclone steps) ...
